### ISSUE TITLE
Inquiry about Command Line API for Automation in Windows PE

### ISSUE THREAD

**Issue by Runninginsilence1** [TalAloni/iSCSIConsole#13]
Hello,
The following content has been generated through translation. 

I am wondering if this application provides a command-line API. I am looking to implement automation within Windows PE.

While the program runs smoothly on my Windows system, I am interested in having it automatically start the iSCSI server upon booting into Windows PE.

Could you please confirm if there are relevant interfaces or APIs available for this purpose?

**Comment by TalAloni** [comment]
Hi, iSCSI Console has a GUI interface that can be run from Windows PE using Mono.
You can use the iSCSI Library to write a console application with a very small effort.

**Comment by Runninginsilence1** [comment]
Thanks for your help. Based on the iSCSI library you wrote, I have successfully created a functional auto-start program. It is now running well. Library is really easy to use and cool.
