### ISSUE TITLE
Request for Write Redirect Functionality 

### ISSUE THREAD

**Issue by vojenfr** [TalAloni/iSCSIConsole#19]
Could you implement new feature on your iSCSI server which would allow the server to redirect write operations to a separate storage device or file (_raw_) ?
Thanks you 
Great Tool !

**Comment by TalAloni** [comment]
Hi, thanks for the feedback.
No - I don't believe Write Redirect conform to the existing model.
You can fork the project and make the necessary changes yourself or hire someone to do it for you - that's why it's open source.
