### ISSUE TITLE
Support for sparse vmdk files

### ISSUE THREAD

**Issue by imbmf** [TalAloni/iSCSIConsole#5]
It is possible to add support for vmdk sparse files? now I am getting following message: "Unsupported Disk Image Format".

**Comment by TalAloni** [comment]
What do you have as 'createType' in the .vmdk?
Currently Monolithic sparse is supported but not 'twoGbMaxExtentSparse'.
I have assumed there would be little demand for 'twoGbMaxExtentSparse', but I would gladly accept a patch. read-only support should be relatively easy so I might be tempted to do just that.

**Comment by imbmf** [comment]
yes you are right create type is: createType="twoGbMaxExtentSparse". I do not have a programming skills to implement patch.

**Comment by TalAloni** [comment]
Is there any specific reason you use this format and not the more common Monolithic sparse?
Would read-only help you at all?

**Comment by imbmf** [comment]
nothing special, thank you!
